### ISSUE TITLE
你好，请问能够分享数据呢？在原网站上没有看到数据。谢谢鹅。

### ISSUE THREAD

**Issue by Evanevaneva** [kunkun1230/Data-analysis#1]

**Comment by kunkun1230** [comment]
你说的是哪个项目数据啊？

**Comment by Evanevaneva** [comment]
“&nbsp;基于K-means聚类的用户用电行为分析”&nbsp;
聚类这个哟 谢谢啦



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kunkun_1230 <notifications@github.com&gt;
发送时间: 2019年10月10日 17:34
收件人: kunkun1230/Data-analysis <Data-analysis@noreply.github.com&gt;
抄送: Evanevaneva <1973329369@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[kunkun1230/Data-analysis] 你好，请问能够分享数据呢？在原网站上没有看到数据。谢谢鹅。 (#1)

**Comment by kunkun1230** [comment]
抱歉，有点忙忘记了哈。
数据有点大，我分享到云盘了：
链接：https://pan.baidu.com/s/1ydLyqyQGZe4ouQrtWnwR7g 
提取码：0sc6

**Comment by Evanevaneva** [comment]
收到谢谢🙏



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kunkun_1230 <notifications@github.com&gt;
发送时间: 2019年10月15日 22:02
收件人: kunkun1230/Data-analysis <Data-analysis@noreply.github.com&gt;
抄送: Evanevaneva <1973329369@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[kunkun1230/Data-analysis] 你好，请问能够分享数据呢？在原网站上没有看到数据。谢谢鹅。 (#1)
